platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  
  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'cloud_firestore'

  # Add any other necessary pods here
end
